SECRET_KEY="YOUR_SECRET_KEY"
DATABASE="NAME_OF_THE_DATABASE_FILE.DB"

MAIL_SERVER = "SMTP_SERVER_NAME"  
MAIL_PORT = 587 
MAIL_USE_TLS = True  
MAIL_USE_SSL = False  
MAIL_USERNAME = "EMAIL_ADDRESS"  
MAIL_PASSWORD = "PASSWORD" 